application: spider-notes
version: 1
api_version: 1
runtime: python27
threadsafe: true

handlers:
- url: /(favicon\.ico)
  mime_type: image/png
  static_files: static/\1
  upload: static/favicon\.ico

- url: /(robots\.txt)
  static_files: static/\1
  upload: static/robots\.txt

- url: /static
  static_dir: static

- url: /.*
  script: spidernotes.app

inbound_services:
- warmup

libraries:
- name: webapp2
  version: latest